# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71975e92fdaf502ad92b1cf63c19d88d936821788a2f99ab4ae8a3eee35e513f1b1490b83722da9bb2d4497c67a86a655a642f187c5ada1b54189e4c74e54c1c

test:
  secret_key_base: 3adf540abb1642ea16715ceb9fb25988a0ba3f6377585883dd1412555981e4132abb87d0f39734583d5c182113e84210d00ca7b8bb1772069f9a39407037f7df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
